### ISSUE TITLE
What is go-more-timers?

### ISSUE THREAD

**Issue by lanzafame** [Kubuxu/go-more-timers#2]
What does it do? Looking at the code there is a thing called a `Gaussian` but it doesn’t mention what it is? There is no README.md or GitHub tagline. Before merging libp2p/go-libp2p-peerstore#89 please fix this so that the new dependency can be understood.

**Comment by Kubuxu** [comment]
Added README and also there is a doc string:
```go
// NewGaussian createos a timer (similar from standard library package time)
// The duration for timer to trigger isn't fully defined.
// It is a Gaussian distribution with mean and standard deviation.
func NewGaussian(mean time.Duration, stddev time.Duration) *Gaussian {
```

Does this resolve this for you?

**Comment by lanzafame** [comment]
README?

**Comment by Kubuxu** [comment]
I've added it already and also mentioned it.

**Comment by lanzafame** [comment]
Ah sorry, was being lazy and only reviewed your comment via email 🙏. I am satisfied, thank you
